# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PantheonScarab < Formula
  desc "Fleet sweep and network discovery — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.0/pantheon-scarab_0.12.0_darwin_amd64.tar.gz"
      sha256 "0edd5f46f0c7a150999deb8252891f2fcde2b0e9f5ede23e27c4d5dd1b428d42"

      define_method(:install) do
        bin.install "pantheon-scarab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.0/pantheon-scarab_0.12.0_darwin_arm64.tar.gz"
      sha256 "4c045482cc522e3184126bb3d1c7971da8d8d7d503112c4f03bee522f132566f"

      define_method(:install) do
        bin.install "pantheon-scarab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.0/pantheon-scarab_0.12.0_linux_amd64.tar.gz"
      sha256 "bcca57e9c482c260276f7e959d3c123c3b31164dfeeed90ec1a4ff84c30456be"
      define_method(:install) do
        bin.install "pantheon-scarab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.0/pantheon-scarab_0.12.0_linux_arm64.tar.gz"
      sha256 "1bb135428885dfbc506047f1b5b1b2e74049019c54d92427995bc8450f4d37e0"
      define_method(:install) do
        bin.install "pantheon-scarab"
      end
    end
  end

  test do
    system "#{bin}/pantheon-scarab", "version"
  end
end
