# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PantheonAnubis < Formula
  desc "Infrastructure scanner and cleaner — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.15.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.15.0/pantheon-anubis_0.15.0_darwin_amd64.tar.gz"
      sha256 "f2b4e58230f302c4eaaa4559459e5ab03a423846f6bff38ce50eb03dacfbdb50"

      define_method(:install) do
        bin.install "pantheon-anubis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.15.0/pantheon-anubis_0.15.0_darwin_arm64.tar.gz"
      sha256 "f442d39294d7ccdd4d9c585f8ef7d0e88eb857c5a705135b6c23b620c64074c2"

      define_method(:install) do
        bin.install "pantheon-anubis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.15.0/pantheon-anubis_0.15.0_linux_amd64.tar.gz"
      sha256 "56c53dfeb3b97de14bf43cdd71e619619598006c29b04ee9084edfac8ccddd0d"
      define_method(:install) do
        bin.install "pantheon-anubis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.15.0/pantheon-anubis_0.15.0_linux_arm64.tar.gz"
      sha256 "ff95a9c3d2c4c4262f796150a49211f8d8304ff4e91ee81b1e46a5769a7f40dd"
      define_method(:install) do
        bin.install "pantheon-anubis"
      end
    end
  end

  test do
    system "#{bin}/pantheon-anubis", "version"
  end
end
