# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PantheonThoth < Formula
  desc "AI project memory with context compression — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.12.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.4/pantheon-thoth_0.12.4_darwin_amd64.tar.gz"
      sha256 "237cc060ea5ec76347d3789f53cda226572eaab90309c117ac26df0d8677f666"

      define_method(:install) do
        bin.install "pantheon-thoth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.4/pantheon-thoth_0.12.4_darwin_arm64.tar.gz"
      sha256 "392052f562138274aa1cc1368b502520389b4e9b2555acf0643a72bd94959c79"

      define_method(:install) do
        bin.install "pantheon-thoth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.4/pantheon-thoth_0.12.4_linux_amd64.tar.gz"
      sha256 "f6738c124673b2603093501307ca8f6e6185ed574db92d3ba69b0ce2d554a73d"
      define_method(:install) do
        bin.install "pantheon-thoth"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.4/pantheon-thoth_0.12.4_linux_arm64.tar.gz"
      sha256 "7e03a829ebf08693a6eb304c5792148bba6d98405f9a4019103a79bb0df269a9"
      define_method(:install) do
        bin.install "pantheon-thoth"
      end
    end
  end

  test do
    system "#{bin}/pantheon-thoth", "version"
  end
end
