# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PantheonAnubis < Formula
  desc "Infrastructure scanner and cleaner — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.0/pantheon-anubis_0.12.0_darwin_amd64.tar.gz"
      sha256 "0855ae4dd085b08cc63406adcc501c19bc48149688be2bcf76a9ddc98d9520c6"

      define_method(:install) do
        bin.install "pantheon-anubis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.0/pantheon-anubis_0.12.0_darwin_arm64.tar.gz"
      sha256 "de84dd4f56c92aa2003f6bb859ad574805c47239b6c729d67dcba04ec60dded6"

      define_method(:install) do
        bin.install "pantheon-anubis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.0/pantheon-anubis_0.12.0_linux_amd64.tar.gz"
      sha256 "9d964955e0020952058f9714cfbbd54ed63829714fd181c0ca153410491362cb"
      define_method(:install) do
        bin.install "pantheon-anubis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.0/pantheon-anubis_0.12.0_linux_arm64.tar.gz"
      sha256 "eb478a878fd812a569aca26d282347566123aef3be942a29be5c77a67788fe46"
      define_method(:install) do
        bin.install "pantheon-anubis"
      end
    end
  end

  test do
    system "#{bin}/pantheon-anubis", "version"
  end
end
