# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PantheonScarab < Formula
  desc "Fleet sweep and network discovery — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.15.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.15.0/pantheon-scarab_0.15.0_darwin_amd64.tar.gz"
      sha256 "24e2a9626cd8b581c1a4e329449cd3420191a757bd2a19ac9a9bfd915e06df77"

      define_method(:install) do
        bin.install "pantheon-scarab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.15.0/pantheon-scarab_0.15.0_darwin_arm64.tar.gz"
      sha256 "281a2f5511ad089e4dbe622713dbc2eba02285120e3ecda234919978c8cbac51"

      define_method(:install) do
        bin.install "pantheon-scarab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.15.0/pantheon-scarab_0.15.0_linux_amd64.tar.gz"
      sha256 "770dc79b1964062e918ae1decae8ce732f26067618296d9b153e449870f97e41"
      define_method(:install) do
        bin.install "pantheon-scarab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.15.0/pantheon-scarab_0.15.0_linux_arm64.tar.gz"
      sha256 "18e367c5e083dc4806ef3186c7e2f3ad4f3b6feaa29998d85516020a78959011"
      define_method(:install) do
        bin.install "pantheon-scarab"
      end
    end
  end

  test do
    system "#{bin}/pantheon-scarab", "version"
  end
end
