# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PantheonMaat < Formula
  desc "Quality assurance and audit engine — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.15.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.15.0/pantheon-maat_0.15.0_darwin_amd64.tar.gz"
      sha256 "77ae5817a033829e2871a77d35ab09a7a2956b6088ce0b2be3671d713f281c41"

      define_method(:install) do
        bin.install "pantheon-maat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.15.0/pantheon-maat_0.15.0_darwin_arm64.tar.gz"
      sha256 "e68b4b097cef9d4880031bc2d561440c4cd033c524d0abe4f29ca42384c1ccf0"

      define_method(:install) do
        bin.install "pantheon-maat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.15.0/pantheon-maat_0.15.0_linux_amd64.tar.gz"
      sha256 "58b64d0ccfa5b04322aef7d86b7112262d3405a7fd7fb473b5136fd8d460a03c"
      define_method(:install) do
        bin.install "pantheon-maat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.15.0/pantheon-maat_0.15.0_linux_arm64.tar.gz"
      sha256 "fb6a9ecf8af1618f5c4374938f227ad81de3286b0c90d0ea4e253cf4535e87b4"
      define_method(:install) do
        bin.install "pantheon-maat"
      end
    end
  end

  test do
    system "#{bin}/pantheon-maat", "version"
  end
end
