# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PantheonMaat < Formula
  desc "Quality assurance and audit engine — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.12.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.2/pantheon-maat_0.12.2_darwin_amd64.tar.gz"
      sha256 "67dc0302d129fc2ba7dee6769a28293ed31a66aa92af1d5ea2fba961a1c204be"

      define_method(:install) do
        bin.install "pantheon-maat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.2/pantheon-maat_0.12.2_darwin_arm64.tar.gz"
      sha256 "eca6d8b1af522347a2aaafafc1c949c1743ad72ec020e0efa35c9d91b0f0c9fb"

      define_method(:install) do
        bin.install "pantheon-maat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.2/pantheon-maat_0.12.2_linux_amd64.tar.gz"
      sha256 "dbb45678d50eda0efa5b8e3316da1eb7453fca65321bfef8d811c9a01ca55294"
      define_method(:install) do
        bin.install "pantheon-maat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.2/pantheon-maat_0.12.2_linux_arm64.tar.gz"
      sha256 "22d513faa75ef8ffde4167cbebe788d6fe3a7b50dcbe9f6eb8d3dd14b8f5761e"
      define_method(:install) do
        bin.install "pantheon-maat"
      end
    end
  end

  test do
    system "#{bin}/pantheon-maat", "version"
  end
end
