# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PantheonGuard < Formula
  desc "System resource monitoring with accelerator detection — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.12.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.4/pantheon-guard_0.12.4_darwin_amd64.tar.gz"
      sha256 "2ecf0ac6174d0f6d2468fca4c3c52eab860661f687a32431a35a2358c39cdb98"

      define_method(:install) do
        bin.install "pantheon-guard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.4/pantheon-guard_0.12.4_darwin_arm64.tar.gz"
      sha256 "75e7fa140e61cbdc636b30412bb71a33f226860cb2ba5899862eb6f68a687771"

      define_method(:install) do
        bin.install "pantheon-guard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.4/pantheon-guard_0.12.4_linux_amd64.tar.gz"
      sha256 "d85c1d34c0e54c6c378ac3b04073d1c35f5e41da2e21455f0c1c662acef3888c"
      define_method(:install) do
        bin.install "pantheon-guard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.4/pantheon-guard_0.12.4_linux_arm64.tar.gz"
      sha256 "7c71d27aad2a31569c79f78ab9fba6812de1d73ee2567f704e8cce1edc960537"
      define_method(:install) do
        bin.install "pantheon-guard"
      end
    end
  end

  test do
    system "#{bin}/pantheon-guard", "version"
  end
end
