# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PantheonThoth < Formula
  desc "AI project memory with context compression — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.12.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.2/pantheon-thoth_0.12.2_darwin_amd64.tar.gz"
      sha256 "d1f85c8fa25baa599a5c2a0a7cc29253958fbda0954e57adb0bc3cb756afe775"

      define_method(:install) do
        bin.install "pantheon-thoth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.2/pantheon-thoth_0.12.2_darwin_arm64.tar.gz"
      sha256 "acc39dc8f3f59c5753e313c6f5fa53eeb70651c11c09d13938e48e8ded4cc1bd"

      define_method(:install) do
        bin.install "pantheon-thoth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.2/pantheon-thoth_0.12.2_linux_amd64.tar.gz"
      sha256 "b135caa9ba6b8e6128ce8282e4dccb68086826a38e421d4ff385088ce1e8ecd6"
      define_method(:install) do
        bin.install "pantheon-thoth"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.2/pantheon-thoth_0.12.2_linux_arm64.tar.gz"
      sha256 "d483ce4333d6291876b5bade228cf9cf87176c79a551383f9c70c3d65b112df1"
      define_method(:install) do
        bin.install "pantheon-thoth"
      end
    end
  end

  test do
    system "#{bin}/pantheon-thoth", "version"
  end
end
