# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PantheonScarab < Formula
  desc "Fleet sweep and network discovery — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.12.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.2/pantheon-scarab_0.12.2_darwin_amd64.tar.gz"
      sha256 "2c6aa9485601d2a5246896d6c4aa3d8dc74e78d7fb56a4ec227fdfd96ad91a68"

      define_method(:install) do
        bin.install "pantheon-scarab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.2/pantheon-scarab_0.12.2_darwin_arm64.tar.gz"
      sha256 "7b617ecb233e6640c3179d4c9ef7530eb7bb2f7968cb5d39e947910781eee1fe"

      define_method(:install) do
        bin.install "pantheon-scarab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.2/pantheon-scarab_0.12.2_linux_amd64.tar.gz"
      sha256 "dcc3784a04d3afc97b6e4598bb5d4dfec2c1b952495283a3376a5041926dc0f4"
      define_method(:install) do
        bin.install "pantheon-scarab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.12.2/pantheon-scarab_0.12.2_linux_arm64.tar.gz"
      sha256 "cf0673e9be430f6dd0e31cd88cd4d20eb67d0073e86ac9ea0008020b5d546bb8"
      define_method(:install) do
        bin.install "pantheon-scarab"
      end
    end
  end

  test do
    system "#{bin}/pantheon-scarab", "version"
  end
end
