# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SirsiAnubis < Formula
  desc "Infrastructure scanner and cleaner — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.17.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.17.1/sirsi-anubis_0.17.1_darwin_amd64.tar.gz"
      sha256 "879336672e29c955b7e2d0c3ed9a50010cb3c1783f383b4a827da37caf5f478f"

      define_method(:install) do
        bin.install "sirsi-anubis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.17.1/sirsi-anubis_0.17.1_darwin_arm64.tar.gz"
      sha256 "08e040a5ae70fcb2095ec10698a2d33bdd12b084c6b4de8a2828b414e262225a"

      define_method(:install) do
        bin.install "sirsi-anubis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.17.1/sirsi-anubis_0.17.1_linux_amd64.tar.gz"
      sha256 "707f54996fb19da082512f4eba8fed60e1a65a5cfa920d33cc06cfed315de419"
      define_method(:install) do
        bin.install "sirsi-anubis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.17.1/sirsi-anubis_0.17.1_linux_arm64.tar.gz"
      sha256 "d865986d7b472039cc53ccaffb00f36f1391b3b234b4631001a7e63c12fbf14c"
      define_method(:install) do
        bin.install "sirsi-anubis"
      end
    end
  end

  test do
    system "#{bin}/sirsi-anubis", "version"
  end
end
