# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SirsiAnubis < Formula
  desc "Infrastructure scanner and cleaner — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.17.0-alpha"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.17.0-alpha/sirsi-anubis_0.17.0-alpha_darwin_amd64.tar.gz"
      sha256 "efe8eb6f3b4173b9ada3e4c24e7fd37d0d5e502fb5bd8b7c765ec8c9354e73d4"

      define_method(:install) do
        bin.install "sirsi-anubis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.17.0-alpha/sirsi-anubis_0.17.0-alpha_darwin_arm64.tar.gz"
      sha256 "7a5e7d40ff37dad8802f5855e8ced3720cb15e73224d119a3bec6f1c7c25e9cf"

      define_method(:install) do
        bin.install "sirsi-anubis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.17.0-alpha/sirsi-anubis_0.17.0-alpha_linux_amd64.tar.gz"
      sha256 "7b6e2fb00b72638e9b8c4da9eba008ab9e47eaa349f044c246e2be08f6cd216d"
      define_method(:install) do
        bin.install "sirsi-anubis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.17.0-alpha/sirsi-anubis_0.17.0-alpha_linux_arm64.tar.gz"
      sha256 "d5a3d1b149fb5c5f4be8b87907cada091d7184f7fc13f9da2c30c8bd5af1cfb3"
      define_method(:install) do
        bin.install "sirsi-anubis"
      end
    end
  end

  test do
    system "#{bin}/sirsi-anubis", "version"
  end
end
