# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SirsiPantheon < Formula
  desc "Unified DevOps Intelligence Platform — One Install, All Deities"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.23.5-beta"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.23.5-beta/sirsi-pantheon_0.23.5-beta_darwin_amd64.tar.gz"
      sha256 "f1566287b377eca9a975b61acf80815508c9f205892c5484f2959eef24141669"

      define_method(:install) do
        bin.install "sirsi"
        bin.install "sirsi-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.23.5-beta/sirsi-pantheon_0.23.5-beta_darwin_arm64.tar.gz"
      sha256 "1aca626981c882811102ae988c85875f7d1f4ef04c9d73106bf4d35e3ac18b39"

      define_method(:install) do
        bin.install "sirsi"
        bin.install "sirsi-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.23.5-beta/sirsi-pantheon_0.23.5-beta_linux_amd64.tar.gz"
      sha256 "aaad9573e7e4fc9e1f1b44d15ce5391591622057d7cfd622e94f1b9d47d1c239"
      define_method(:install) do
        bin.install "sirsi"
        bin.install "sirsi-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.23.5-beta/sirsi-pantheon_0.23.5-beta_linux_arm64.tar.gz"
      sha256 "d4614e7c3736fda906039d1dfaca4e3d63afc58c2e28b33296b2697134e8f873"
      define_method(:install) do
        bin.install "sirsi"
        bin.install "sirsi-agent"
      end
    end
  end

  test do
    system "#{bin}/sirsi", "version"
  end
end
