# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SirsiThoth < Formula
  desc "AI project memory with context compression — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.17.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.17.2/sirsi-thoth_0.17.2_darwin_amd64.tar.gz"
      sha256 "6831a53bf88d5ba6bfab4855ee8046f233d82feb3293da2ec79cfc433c4e799f"

      define_method(:install) do
        bin.install "sirsi-thoth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.17.2/sirsi-thoth_0.17.2_darwin_arm64.tar.gz"
      sha256 "0bc6830397405cf62b65a75c6dbb2c9c414eb5b4c1977b207fa5ec442d1700f6"

      define_method(:install) do
        bin.install "sirsi-thoth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.17.2/sirsi-thoth_0.17.2_linux_amd64.tar.gz"
      sha256 "5ff7dbbd1ca7efec2f9b7868433d8b95e52636c1b642fb2ae59e5b72152b79d9"
      define_method(:install) do
        bin.install "sirsi-thoth"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.17.2/sirsi-thoth_0.17.2_linux_arm64.tar.gz"
      sha256 "abef1486650526c1bdcd507c9a870bc01ea431d0f3a236b8b0380d4c7fcb5091"
      define_method(:install) do
        bin.install "sirsi-thoth"
      end
    end
  end

  test do
    system "#{bin}/sirsi-thoth", "version"
  end
end
