# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SirsiScarab < Formula
  desc "Fleet sweep and network discovery — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.23.0-beta"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.23.0-beta/sirsi-scarab_0.23.0-beta_darwin_amd64.tar.gz"
      sha256 "13a9e14c1360c6f84ad4940a8ea5f4502b4a5e8f6eb8270a0539e56cf8c041d7"

      define_method(:install) do
        bin.install "sirsi-scarab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.23.0-beta/sirsi-scarab_0.23.0-beta_darwin_arm64.tar.gz"
      sha256 "c33c8e6663b5c86a571d651df301cd38dea1a1522b83545934d42247a106428c"

      define_method(:install) do
        bin.install "sirsi-scarab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.23.0-beta/sirsi-scarab_0.23.0-beta_linux_amd64.tar.gz"
      sha256 "679347803f778cfa3f194482b9540e6541f1656b54971b34871716c225fc82d1"
      define_method(:install) do
        bin.install "sirsi-scarab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.23.0-beta/sirsi-scarab_0.23.0-beta_linux_arm64.tar.gz"
      sha256 "90589814a6d999fdb3a806febfe7cd5ff731aa5808b1454700c8dfabff0b2671"
      define_method(:install) do
        bin.install "sirsi-scarab"
      end
    end
  end

  test do
    system "#{bin}/sirsi-scarab", "version"
  end
end
