# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SirsiScarab < Formula
  desc "Fleet sweep and network discovery — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.17.0-alpha"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.17.0-alpha/sirsi-scarab_0.17.0-alpha_darwin_amd64.tar.gz"
      sha256 "0f74069a10b0a29ef432f403a0672cb29fc6d4ef576d853df179eba9df2364c5"

      define_method(:install) do
        bin.install "sirsi-scarab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.17.0-alpha/sirsi-scarab_0.17.0-alpha_darwin_arm64.tar.gz"
      sha256 "96d9e01dfbb72f58b5f49747b6496016f011e311516c0922fea86cb507b83a7a"

      define_method(:install) do
        bin.install "sirsi-scarab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.17.0-alpha/sirsi-scarab_0.17.0-alpha_linux_amd64.tar.gz"
      sha256 "71a2b70bea7a7ee741cb0049f1bc63d97b674b8603da1ffc8a1e7f7427abe9cd"
      define_method(:install) do
        bin.install "sirsi-scarab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.17.0-alpha/sirsi-scarab_0.17.0-alpha_linux_arm64.tar.gz"
      sha256 "3296cf99def5340fb6bdfc544fc1b9977ec0cf45349a1ee945e77a67e39fd95c"
      define_method(:install) do
        bin.install "sirsi-scarab"
      end
    end
  end

  test do
    system "#{bin}/sirsi-scarab", "version"
  end
end
