# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SirsiMaat < Formula
  desc "Quality assurance and audit engine — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.16.0-alpha"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.16.0-alpha/sirsi-maat_0.16.0-alpha_darwin_amd64.tar.gz"
      sha256 "817d4df500dfe4c08cd1132fef13a3cd4d656761180b54935ad28c8347a6ec3d"

      define_method(:install) do
        bin.install "sirsi-maat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.16.0-alpha/sirsi-maat_0.16.0-alpha_darwin_arm64.tar.gz"
      sha256 "e0ab555d3a9784016ca8563bf92bbb78220ea1b82664a10ebbf92c385a68cdee"

      define_method(:install) do
        bin.install "sirsi-maat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.16.0-alpha/sirsi-maat_0.16.0-alpha_linux_amd64.tar.gz"
      sha256 "b78db5bfce206893c501709f62b941c0ac35b7096f6bba0525e56062d45fcbbf"
      define_method(:install) do
        bin.install "sirsi-maat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.16.0-alpha/sirsi-maat_0.16.0-alpha_linux_arm64.tar.gz"
      sha256 "4299be1916d4e89252cf6bf603755253481be070669cde88d2d5a9c54fb2ac67"
      define_method(:install) do
        bin.install "sirsi-maat"
      end
    end
  end

  test do
    system "#{bin}/sirsi-maat", "version"
  end
end
