# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SirsiGuard < Formula
  desc "System resource monitoring with accelerator detection — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.18.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.18.0/sirsi-guard_0.18.0_darwin_amd64.tar.gz"
      sha256 "4710e9c7ceba45fba1ae4e870b0da3dfbd80bd3df5e3b57b5ae52f6615e6b60f"

      define_method(:install) do
        bin.install "sirsi-guard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.18.0/sirsi-guard_0.18.0_darwin_arm64.tar.gz"
      sha256 "eeefeb92096c6556458de724196837d3fdb229a906ac3b392eb2c7695abcd38e"

      define_method(:install) do
        bin.install "sirsi-guard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.18.0/sirsi-guard_0.18.0_linux_amd64.tar.gz"
      sha256 "a89f1d21cc169f22761a2bc9914b3474b223aaac372ff4b6597d6f11688c5b38"
      define_method(:install) do
        bin.install "sirsi-guard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.18.0/sirsi-guard_0.18.0_linux_arm64.tar.gz"
      sha256 "e74e5d405c1c4df5c6ecda0565ee698e116d356a7321ac51ad0717679e9a36b1"
      define_method(:install) do
        bin.install "sirsi-guard"
      end
    end
  end

  test do
    system "#{bin}/sirsi-guard", "version"
  end
end
