# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SirsiScarab < Formula
  desc "Fleet sweep and network discovery — standalone deity"
  homepage "https://github.com/SirsiMaster/sirsi-pantheon"
  version "0.18.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.18.0/sirsi-scarab_0.18.0_darwin_amd64.tar.gz"
      sha256 "d28e0e8d9cfb77ded3ac17277b283a47cad3a8b97db5f36e26be9a7cbd541ec9"

      define_method(:install) do
        bin.install "sirsi-scarab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.18.0/sirsi-scarab_0.18.0_darwin_arm64.tar.gz"
      sha256 "d43455d08bf7c5b00a64a3d82e6cb8081994a229021e2b40c139665b3b0b2f7d"

      define_method(:install) do
        bin.install "sirsi-scarab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.18.0/sirsi-scarab_0.18.0_linux_amd64.tar.gz"
      sha256 "ee8e54a19ddd6e135435fe71543d7b9fbe1a2f0fb1a86d9b3ca478aefad69959"
      define_method(:install) do
        bin.install "sirsi-scarab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SirsiMaster/sirsi-pantheon/releases/download/v0.18.0/sirsi-scarab_0.18.0_linux_arm64.tar.gz"
      sha256 "36b1def92a896a665b3ee5ff13df32975cb8662935376ace782457eb263816d4"
      define_method(:install) do
        bin.install "sirsi-scarab"
      end
    end
  end

  test do
    system "#{bin}/sirsi-scarab", "version"
  end
end
